# Math Code Interpreter Training Configuration
# Multi-turn agent with code interpreter using agent_loop algorithm
# Use with: python math_code_interpreter_client.py

# Project settings
project_name: opentinker
experiment_name: math_code_interpreter

# Logging
logger_backends: ["console", "wandb"]

# Tracing (optional)
enable_tracing: true
weave_project: null

# WandB (optional)
wandb_key: null

# Model and tokenizer
tokenizer_path: null

# Data paths
data_path: null        # Path to training data (parquet/JSON/JSONL)
val_data_path: null    # Path to validation data (parquet/JSON/JSONL)

# Training parameters
batch_size: 32
num_workers: 0
# Training duration - set ONE of these (num_steps takes precedence if both set)
num_epochs: 10        # Number of epochs (null = use num_steps)
num_steps: null       # Total training steps (null = use num_epochs)
save_freq: 100
test_freq: 50         # Validation frequency (every N steps)

# Validation parameters
val_batch_size: 64    # Total validation samples

# Generation parameters
temperature: 1
top_p: 1
max_new_tokens: 8192  # TOTAL response budget for entire trajectory
max_prompt_tokens: 2048

# Algorithm - agent_loop for multi-turn with GymEnvironmentInteraction
algorithm: "agent_loop"

# RL Algorithm settings (passed to server via scheduler)
# adv_estimator: "grpo" or "gae" (for PPO)
adv_estimator: "grpo"
# rollout_n: number of samples per prompt for GRPO (only used when adv_estimator=grpo)
rollout_n: 8

# Multi-turn configuration
multi_turn:
  max_user_turns: 5         # Max environment responses (code execution results)
  max_assistant_turns: 5    # Max LLM responses  
  max_tokens_per_turn: 1024  # Per-turn response limit
  weave_project: null
  experiment_name: "math_code_interpreter"

# Interaction configuration (GymEnvironmentInteraction -> CodeInterpreterMathGame server)
interaction:
  name: math_code_interpreter
  class_path: opentinker.environment.gym_environment_interaction.GymEnvironmentInteraction
  config:
    env_host: 0.0.0.0
    env_port: 8088
    env_endpoint: http://${interaction.config.env_host}:${interaction.config.env_port}
    max_steps: 5    # Max interaction steps (code executions)

# Scheduler settings
scheduler_url: "http://0.0.0.0:8780"
scheduler_api_key: null

# GPU settings
num_gpus: 4

